### DISCUSSION TITLE
Blogpost 15

### DISCUSSION THREAD

**Discussion by tr45h3r** [LeonRother/SE_Platzverwaltung#20] [General]
# 📝 Blogeintrag – Erfasste Software-Metriken

## 1. Unsere gewählten Metriken

- **Code Smells**
- **Cyclomatic Complexity / Return-Vereinfachungen**
- **Code Duplication**

---

### ✅ 1. Code Smells (SonarLint)

Wir haben **SonarLint** in **WebStorm** installiert und eine Analyse des gesamten Projekts durchgeführt.  
Dabei wurden folgende **Code Smells** erkannt:

- In der Datei `SelectionView.vue` befindet sich ein **offener TODO-Kommentar**, der auf eine **unvollständige Implementierung** hinweist:
  
  > _"Complete the task associated to this 'TODO' comment."_
  

SonarLint hat uns diesen Hinweis direkt im **SonarLint Tool Window** angezeigt, inklusive Link zur betroffenen Stelle.

---

### ✅ 2. Cyclomatic Complexity / Return-Vereinfachungen (SonarLint)

Ebenfalls durch **SonarLint** wurde in der Datei `index.js` eine **unnötig komplexe if-else-Struktur** erkannt.  
Die Empfehlung von SonarLint lautet:

> _"Replace this if-then-else flow by a single return statement."_

Diese Rückmeldung hilft, den **Code einfacher, klarer und wartbarer** zu gestalten, was direkt zur **Reduzierung der Cyclomatic Complexity** beiträgt.

---

### ✅ 3. Code Duplication (WebStorm Duplicate Finder)

Mit dem **WebStorm-Tool „Locate Duplicates“** wurden zwei **nahezu identische CSS-Blöcke** in der Datei  
`index-Df-VqX3D.css` gefunden.

Die gefundenen Duplikate sind:

```css
*,:before,:after { --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; }
```

und

```css
::backdrop { --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; }
```

Diese sollten **konsolidiert oder entfernt** werden, um die **Wartbarkeit zu erhöhen** und **Redundanzen zu vermeiden**.

## 3. Fazit

Mit **SonarLint** und dem **WebStorm Duplicate Finder** konnten wir **mehrere Qualitätsprobleme** gezielt identifizieren:

- **Unvollständige Implementierungen** (TODOs)
- **Unnötige Komplexität in der Logik**
- **Redundanter Code**

Diese Erkenntnisse helfen uns, den **Code robuster, lesbarer und wartbarer** zu gestalten.
